### ISSUE TITLE
when runing "python3 setup.py bdist_wheel" face problem 

### ISSUE THREAD

**Issue by Jasper-kk** [VinAIResearch/Open3DIS#22]
when runing "python3 setup.py bdist_wheel" face
 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running bdist_wheel
running build
running build_ext
building 'pointnet2._ext' extension
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setup(
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
    self.run_command("build")
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
(Open3DIS) root@b9713f2641ed:/workspace/Open3DIS/segmenter3d/ISBNet/isbnet/pointnet2# python3 setup.py bdist_wheel
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
running bdist_wheel
running build
running build_ext
building 'pointnet2._ext' extension
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setup(
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
    self.run_command("build")
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by PhucNDA** [comment]
Hi @Jasper-kk,

I think this might be CUDA driver issue. You could check at: [this link](https://github.com/IDEA-Research/GroundingDINO/issues/8)
